### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by parveenrhce** [savitojs/secret-santa-finder-script#1]
I'm getting error while running this script. Screenshot attached herewith.

[User1@tests_machine secret-santa-finder-script-master]$ ./secret_santa.py
Welcome.. What is your nick name? [ENTER] KK     

Hey KK!, Hold on!! Looking for your secret santa

Traceback (most recent call last):
  File "./secret_santa.py", line 16, in <module>
    _from.remove(user_name)
ValueError: list.remove(x): x not in list
[User1@tests_machine secret-santa-finder-script-master]$

![image](https://cloud.githubusercontent.com/assets/24706720/21410603/e4fece68-c807-11e6-9051-1bbe2d762934.png)

**Comment by savitojs** [comment]
Fixed minor issues.. and updated README
check once again. Closing the issue.
